#!/bin/env ruby

emacs_distros = Dir[File.expand_path(File.join("~", "emacs", "distributions", "*"))]
                .select { |d| File.directory? d }
                .map {|d| d.split(File::SEPARATOR).last }
puts emacs_distros
if emacs_distros.include? ARGV[0]
  cmd = "rm ~/.emacs.d; ln -sf ~/emacs/distributions/#{ARGV[0]}/.emacs.d ~/.emacs.d"
  puts cmd
  system cmd
  system "emacs &"
end
